services:
- type: web
  name: ghost
  env: docker
  autoDeploy: false
  disk:
    name: ghost
    mountPath: /var/lib/ghost/content
    sizeGB: 10 #Feel free to change this to suit your needs.
  envVars:
      DB_CLIENT: 'pg'
      DB_HOST: 'ap-northeast-2.16bffd9f-a8c7-4699-a2f6-51504ab0a509.aws.ybdb.iomysql-db'
      DB_PORT: '5433'
      DB_DATABASE: 'yugabyte'
      DB_USER: 'admin'
      DB_PASSWORD: 'eLPHklxJ2cWj39kRmczwxfnPtYKMLT'