services:
- type: web
  name: ghost
  env: docker
  autoDeploy: false
  disk:
    name: ghost
    mountPath: /var/lib/ghost/content
    sizeGB: 10 #Feel free to change this to suit your needs.
  envVars:
    - key: database__client
      value: postgresql
    - key: database__connection__host
      fromService:
        type: pserv
        name: postgresql
        property: host
    - key: database__connection__database
      value: yugabyte
    - key: database__connection__user
      value: admin
    - key: database__connection__password
      fromService:
        type: pserv
        name: postgresql
        envVarKey: eLPHklxJ2cWj39kRmczwxfnPtYKMLT

- type: pserv
  name: postgresql
  plan: standard
  env: docker
  repo: https://github.com/render-examples/mysql
  autoDeploy: false
  disk:
    name: postgresql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
    - key: postgresql_DATABASE
      value: yugabyte
    - key: postgresql_USER
      value: admin
    - key: postgresql_PASSWORD
      generateValue: true
    - key: postgresql_ROOT_PASSWORD
      generateValue: true

